name: Run HTTP Server Script

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run PowerShell script
      shell: pwsh
      run: |
        $url = "${{ github.workspace }}/http_server.ps1"
        $scriptContent = Get-Content -Path $url -Raw
        Invoke-Expression -Command $scriptContent
