name: Run HTTP Server Script

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run PowerShell script
      run: |
        # Fetch the content of the script from the URL with UTF-8 encoding
        $url = "./http_server.ps1"
        $response = Invoke-WebRequest -Uri $url
        $scriptContent = [System.Text.Encoding]::UTF8.GetString($response.Content)
        
        # Execute the fetched script content
        Invoke-Expression -Command $scriptContent
